---

# INCF :: this is the main flask skeleton that Satra started

- hosts: engineservers
  user: vagrant
  sudo: True

  vars_files:
    - vars.yml

  tasks:
    - include: tasks/engineserver.yml

    - name: link /vagrant to {{ webapps_dir }}/{{ app_name}}
      file: force=yes src=/vagrant path={{ webapps_dir }}/{{ app_name }} state=link

    - name: install gunicorn
      sudo: False
      shell: $HOME/anaconda/bin/pip install gunicorn executable=/bin/bash

  handlers:
    - include: handlers.yml
